name: mlops-example-cv
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python cnn.py
          
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          
          cml-publish Train-Val_ACC_Curve.png --md >> report.md
          
          cml-send-comment report.md
